{{- if .Values.pullSecret.data }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "moodle.basename" . }}-pull-secret
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "moodle.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.pullSecret.data  }}
{{- end }}