{{- if not .Values.moodle.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "moodle.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "moodle.labels" . | nindent 4 }}
stringData:
  MOODLE_UPGRADEKEY: {{ .Values.moodle.secrets.MOODLE_UPGRADEKEY | quote }}
  MOODLE_ADMIN_PASSWORD: {{ .Values.moodle.secrets.MOODLE_ADMIN_PASSWORD | quote }}
{{- end }}

