workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - package

include:
  - component: $CI_SERVER_FQDN/gitlabci-components/image-build-multiplatform/build@1.1.0
    inputs:
      name: moodle
      target: moodle-custom
      platform:
        - linux/amd64
      image_repos:
        - registry.rz1.metaways.net/devops
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.2.1
    inputs:
      name: moodle
