---
# Source: moodle/templates/moodle/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
stringData:
  MOODLE_UPGRADEKEY:
---
# Source: moodle/templates/moodle/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
# Source: moodle/templates/moodle/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
spec:
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: moodle
---
# Source: moodle/templates/moodle/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
spec:
  replicas: 
  selector:
    matchLabels:
      app.kubernetes.io/name: moodle
      app.kubernetes.io/instance: test
      app.kubernetes.io/component: moodle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moodle
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: moodle-0.0.0
        app.metaways.net/team: 
        app.metaways.net/name: 
        app.kubernetes.io/component: moodle
        # app.metaways.net/software: 
        app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
      annotations:
        checksum/secret: 1233a02348c7bc246057afaf032788a9cd0e0ff331925c34538ac675c1e25449
    spec:
      serviceAccount: 
      containers:
        - name: moodle

          image: dockerregistry.metaways.net/se/moodle-chart/moodle:4.5.1-mw0shaee56bdff
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Gi
            requests:
              cpu: 500m
              memory: 512Gi
          envFrom:
            - secretRef:
                name: moodle-test-moodle
          env:
            
            - name: POSTGRES_HOST
              value: 
            - name: POSTGRES_DB
              value: 
            - name: POSTGRES_USER
              value: 
            - name: POSTGRES_PASSWORD
              value: 
            - name: POSTGRES_SSLMODE
              value: "true"
          securityContext:
          volumeMounts:
            - name: data
              mountPath: /var/lib/moodle
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: moodle-test-moodle
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
---
# Source: moodle/templates/moodle/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: 
          containers:
            - name: moodle

              image: dockerregistry.metaways.net/se/moodle-chart/moodle:4.5.1-mw0shaee56bdff
              imagePullPolicy: IfNotPresent

              command:
                - bash
                - -c
                - |
                  echo running cronjob
              resources:
              limits:
                memory: 512Gi
              requests:
                cpu: 500m
                memory: 512Gi
    
              envFrom:
                - secretRef:
                    name: moodle-test-moodle
    
              env:
                
                - name: POSTGRES_HOST
                  value: 
                - name: POSTGRES_DB
                  value: 
                - name: POSTGRES_USER
                  value: 
                - name: POSTGRES_PASSWORD
                  value: 
                - name: POSTGRES_SSLMODE
                  value: "true"
    
              securityContext:
    
              volumeMounts:
                - name: data
                  mountPath: /var/lib/moodle
    
          volumes:
            - name: data
              persistentVolumeClaim:
                  claimName: moodle-test-moodle
    
          securityContext:
            fsGroup: 33
            fsGroupChangePolicy: OnRootMismatch
---
# Source: moodle/templates/moodle/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle-test-moodle
  namespace: "moodle-test"
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
spec:
  rules:
    - host: REQUIRED
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moodle-test-moodle
                port:
                  number: 80
  tls:
    - hosts:
        - "REQUIRED"
      secretName: REQUIRED-tls
---
# Source: moodle/templates/moodle/hooks/apply.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: moodle-test-moodle-apply
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
spec:
  template:
    metadata:
      name: moodle-test-moodle-apply
    spec:
      restartPolicy: Never
      serviceAccount: 
      containers:
        - name: moodle-apply

          image: "dockerregistry.metaways.net/se/moodle-chart/moodle:4.5.1-mw0shaee56bdff"
          imagePullPolicy: 
          command:
            - bash
            - -c
            - |
              echo running hook
          resources:
            limits:
              memory: 512Gi
            requests:
              cpu: 500m
              memory: 512Gi
  
            envFrom:
              - secretRef:
                  name: moodle-test-moodle
  
            env:
              
              - name: POSTGRES_HOST
                value: 
              - name: POSTGRES_DB
                value: 
              - name: POSTGRES_USER
                value: 
              - name: POSTGRES_PASSWORD
                value: 
              - name: POSTGRES_SSLMODE
                value: "true"
  
            securityContext:
  
            volumeMounts:
              - name: data
                mountPath: /var/lib/moodle
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: moodle-test-moodle
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
---
# Source: moodle/templates/moodle/hooks/maintenanceoff.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: moodle-test-moodle-maintenanceoff
  labels:
    app.kubernetes.io/name: moodle
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: moodle-0.0.0
    app.metaways.net/team: 
    app.metaways.net/name: 
    app.kubernetes.io/component: moodle
    # app.metaways.net/software: 
    app.kubernetes.io/version: "4.5.1-mw0shaee56bdff"
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
spec:
  template:
    metadata:
      name: moodle-test-moodle-maintenanceoff
    spec:
      restartPolicy: Never
      serviceAccount: 
      containers:
        - name: moodle-maintenanceoff

          image: "dockerregistry.metaways.net/se/moodle-chart/moodle:4.5.1-mw0shaee56bdff"
          imagePullPolicy: 
          command:
            - bash
            - -c
            - |
              echo running hook
          resources:
            limits:
              memory: 512Gi
            requests:
              cpu: 100m
              memory: 512Gi
  
            envFrom:
              - secretRef:
                  name: moodle-test-moodle
  
            env:
              
              - name: POSTGRES_HOST
                value: 
              - name: POSTGRES_DB
                value: 
              - name: POSTGRES_USER
                value: 
              - name: POSTGRES_PASSWORD
                value: 
              - name: POSTGRES_SSLMODE
                value: "true"
  
            securityContext:
  
            volumeMounts:
              - name: data
                mountPath: /var/lib/moodle
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: moodle-test-moodle
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
