releases:
  - name: dev
    kubeContext: moodle-dev-cluster
    namespace: moodle-dev
    chart: ../charts/moodle
    secrets:
      - secrets.sops.yaml
    values:
      - moodle:
          hooks:
            apply:
              enabled: false
            maintenanceoff:
              enabled: false
          deployment:
            replicas: 2
          persistence:
            storageClassName: csi-cephfs-sc
            resources:
              requests:
                storage: 70Gi
          secrets:
            MOODLE_UPGRADEKEY: notsecureqrequireschanging
            MOODLE_ADMIN_PASSWORD: admin
          ingress:
            annotations: 
              kubernetes.io/tls-acme: "true"
        database:
          db: app
          userSecret: postgres-app-owner-user
          connectionConfigMap: postgres.db-rw-connection
          sslmode: true
        redis:
          connectionConfigMap: redis.cache-connection
        jobAnnotations:
        metadata:
          team: se
      - debug:
          diagnoseMode:
            moodleapply:
              enabled: false
              command: [tail, -f, /dev/null]
            moodlemaintenanceoff:
              enabled: false
              command: [tail, -f, /dev/null]
            moodle:
              enabled: false
              command: [tail, -f, /dev/null]
          securityContext:
            moodle:
              enabled: false