# from moodle docs: use this -> is for 4.5 ours defently not. the try_files and set $path_info is new
server {
    # rootless nginx
    # moodle redirects to this port :( - set sysctls net.ipv4.ip_unprivileged_port_start = 0
    listen *:80;

    server_name _;
    client_max_body_size 512m;

    root /var/www/moodle/public;

    index index.php;

    # "The following configuration is known to work with Moodle 4.5 and above." => Lets trust it => the router dose not seem to work probably ..., but moodle works
    location ~ \.php(/|$) {
        # Split the path info based on URI.
        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        # Note: Store the original path_info. It will be wiped out in a moment by try_files.
        set $path_info $fastcgi_path_info;

        # Look for the php file. If not round then jump to @routed.
        try_files $fastcgi_script_name $fastcgi_script_name/;

        # File was found - pass to fastcgi.
        fastcgi_pass   localhost:9000;
        include        fastcgi_params;

        # Re-apply the path_info after including fastcgi_params.
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    # moodles docs say to use "try_files $uri /r.php;" this dose not work for me. / and /my do not work. I expect they should use index.php and are not routed! Therefor i added $uri/ to (check if a dir for the uri exists, and then) use index.php.
    location / {
        try_files $uri $uri/ /r.php$is_args$args;
    }

    # Hide all dot files but allow "Well-Known URIs" as per RFC 5785
    location ~ /\.(?!well-known).* {
        return 404;
    }
    
    # This should be after the php fpm rule and very close to the last nginx ruleset.
    # Don't allow direct access to various internal files. See MDL-69333
    location ~ (/vendor/|/node_modules/|composer\.json|/readme|/README|readme\.txt|/upgrade\.txt|/UPGRADING\.md|UPGRADING\-CURRENT\.md|db/install\.xml|/fixtures/|/behat/|phpunit\.xml|\.lock|environment\.xml) {
        deny all;
        return 404;
    }

    # Todo: remove if router works
    # Fixes: moodle security report. The router problems cause /doesnotexist to return 500, and fail the check.
    location /doesnotexist {
        deny all;
        return 404;
    }

    # from moodle vm
    location ~ ^/uploads/(.+\.php$) {
        deny all;
    }

    # mw standard deny
    location ~ (\.(bak|config|sql(\.zip|\.gz|\.bz2)?|ini|log|sh|inc|swp|t3d)|~)$ {
        deny all;
    }

    # mw standard deny
    location ~ (/\.svn/|/CVS/|/\.ht|/\.ts|/\.git) {
        deny all;
    }

    # 'X-Accel-Redirect
    location /dataroot/ {
        internal;
        alias /var/lib/moodle;
    }
}