moodle:
  hooks:
    apply:
      enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
    maintenanceoff:
      enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  cronjob:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  deployment:
    image:
      repository: registry.rz1.metaways.net/devops/moodle
      tag: 4.5.1-rc2
      imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    replicas: 2
  persistence:
    accessMode: ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    storageClassName:
    existingPvc:
  secrets:
    existingSecret:
    MOODLE_UPGRADEKEY: #REQUIRED
  ingress:
    enabled: true
    hostname: REQUIRED
    annotations: 
      # kubernetes.io/tls-acme: "true"
database:
  host: #REQUIRED if connectionConfigMap is not set
  db: #REQUIRED
  user: #REQUIRED if userSecret is not set
  password: #REQUIRED if userSecret is not set
  userSecret: 
  connectionConfigMap: 
  sslmode: true
pullSecret:
  data: #OPTIONAL
jobAnnotations:
metadata:
  team: #REQUIRED
  name:
debug:
  diagnoseMode:
    moodleapply:
      enabled: false
      command: [tail, -f, /dev/null]
    moodlemaintenanceoff:
      enabled: false
      command: [tail, -f, /dev/null]
    moodle:
      enabled: false
      command: [tail, -f, /dev/null]